from slack_sdk import WebClient
from slack_bolt.adapter.fastapi import SlackRequestHandler
from slack_bolt import App
from fastapi import FastAPI, Request, BackgroundTasks
from agents import team_agents_slack
from config import settings
from utils import get_logger

logger = get_logger()


logger.info("Starting Slack bot...")
# Initialize the Slack Bolt app
slack_app = App(
    token=settings.SLACK_TOKEN, signing_secret=settings.SLACK_SIGNING_SECRET
)

# Initialize FastAPI app
fastapi_app = FastAPI()
handler = SlackRequestHandler(slack_app)


@fastapi_app.get("/health")
async def health_check():
    return {"status": "healthy"}


async def process_mention(event_data: dict) -> None:
    """
    Process events with production-grade Redis deduplication.

    This function checks if an event has already been processed by using Redis
    to lock the event ID. If the event is a duplicate, it skips processing.
    If the event is unique, it processes the event, cleans up the text,
    and sends a response via Slack.

    Args:
        event_data (dict): The event data received from Slack, containing event details such as the event ID, text, and channel.

    Returns:
        None: This function does not return any value, it only performs side effects (logging, sending messages).
    """

    try:
        logger.info(f"Processing event: {event_data}")
        text = event_data["event"]["text"]  # Get the text from the event data
        mention = f"<@{settings.SLACK_BOT_USER_ID}>"  # Format the bot mention
        cleaned_text = text.replace(
            mention, ""
        ).strip()  # Remove the mention from the text

        logger.info(f"Processing mention: {cleaned_text}")
        response = team_agents_slack.run(
            cleaned_text
        ).content  # Process the cleaned text with the bot

        # Use WebClient to send the response via Slack
        slack_client = WebClient(token=settings.SLACK_TOKEN)
        slack_client.chat_postMessage(
            channel=event_data["event"]["channel"],  # The Slack channel
            text=response,  # The response generated by the bot
        )
    except Exception as e:
        # Log any errors that occur during processing
        logger.error(f"Error processing slack bot mention: {e}")


@slack_app.event("app_mention")
def handle_mentions(body: dict, say):
    logger.info(f"Received mention (acknowledged): {body['event']['text']}")
    # Just acknowledge - processing happens in process_mention()


@fastapi_app.post("/slack/events")
async def endpoint(req: Request, background_tasks: BackgroundTasks):
    """
    FastAPI endpoint that:
    1. Immediately responds to Slack with 200 OK.
    2. Processes events in the background.
    """
    try:
        # Parse the request body (but don't fully process yet)
        body = await req.json()

        # Let Slack Bolt verify the request (signing secret, etc.)
        response = await handler.handle(req)

        # If it's an event (like app_mention), process it in the background
        if body.get("type") == "event_callback":
            background_tasks.add_task(process_mention, body)

        return response
    except Exception as e:
        logger.error(f"Slack event handler error: {e}")
        raise
